//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Customer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Customer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Customer", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Account_Comment {
            get {
                return ResourceManager.GetString("Account_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Edit.
        /// </summary>
        internal static string Account_Edit {
            get {
                return ResourceManager.GetString("Account_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string Account_UserName {
            get {
                return ResourceManager.GetString("Account_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact Note.
        /// </summary>
        internal static string AddNewContactNote {
            get {
                return ResourceManager.GetString("AddNewContactNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Editing.
        /// </summary>
        internal static string AddressEdit {
            get {
                return ResourceManager.GetString("AddressEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Info.
        /// </summary>
        internal static string AddressInfo {
            get {
                return ResourceManager.GetString("AddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address.
        /// </summary>
        internal static string AddressNew {
            get {
                return ResourceManager.GetString("AddressNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        internal static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address_mc {
            get {
                return ResourceManager.GetString("Address_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Address_mf_AddressType {
            get {
                return ResourceManager.GetString("Address_mf_AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_AddressType_Description {
            get {
                return ResourceManager.GetString("Address_mf_AddressType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Address_mf_ApplicationId {
            get {
                return ResourceManager.GetString("Address_mf_ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Address_mf_City {
            get {
                return ResourceManager.GetString("Address_mf_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_City_Description {
            get {
                return ResourceManager.GetString("Address_mf_City_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Address_mf_Contact {
            get {
                return ResourceManager.GetString("Address_mf_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        internal static string Address_mf_CountryCode {
            get {
                return ResourceManager.GetString("Address_mf_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_CountryCode_Description {
            get {
                return ResourceManager.GetString("Address_mf_CountryCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        internal static string Address_mf_CountryName {
            get {
                return ResourceManager.GetString("Address_mf_CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_CountryName_Description {
            get {
                return ResourceManager.GetString("Address_mf_CountryName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Phone.
        /// </summary>
        internal static string Address_mf_DaytimePhoneNumber {
            get {
                return ResourceManager.GetString("Address_mf_DaytimePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_DaytimePhoneNumber_Description {
            get {
                return ResourceManager.GetString("Address_mf_DaytimePhoneNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Address_mf_Email {
            get {
                return ResourceManager.GetString("Address_mf_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_Email_Description {
            get {
                return ResourceManager.GetString("Address_mf_Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening Phone.
        /// </summary>
        internal static string Address_mf_EveningPhoneNumber {
            get {
                return ResourceManager.GetString("Address_mf_EveningPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_EveningPhoneNumber_Description {
            get {
                return ResourceManager.GetString("Address_mf_EveningPhoneNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Address_mf_FirstName {
            get {
                return ResourceManager.GetString("Address_mf_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_FirstName_Description {
            get {
                return ResourceManager.GetString("Address_mf_FirstName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default.
        /// </summary>
        internal static string Address_mf_IsDefault {
            get {
                return ResourceManager.GetString("Address_mf_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Address_mf_LastName {
            get {
                return ResourceManager.GetString("Address_mf_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_LastName_Description {
            get {
                return ResourceManager.GetString("Address_mf_LastName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line #1.
        /// </summary>
        internal static string Address_mf_Line1 {
            get {
                return ResourceManager.GetString("Address_mf_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_Line1_Description {
            get {
                return ResourceManager.GetString("Address_mf_Line1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line #2.
        /// </summary>
        internal static string Address_mf_Line2 {
            get {
                return ResourceManager.GetString("Address_mf_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_Line2_Description {
            get {
                return ResourceManager.GetString("Address_mf_Line2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Address_mf_Name {
            get {
                return ResourceManager.GetString("Address_mf_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_Name_Description {
            get {
                return ResourceManager.GetString("Address_mf_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Address_mf_Organization {
            get {
                return ResourceManager.GetString("Address_mf_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        internal static string Address_mf_OrganizationName {
            get {
                return ResourceManager.GetString("Address_mf_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string Address_mf_PostalCode {
            get {
                return ResourceManager.GetString("Address_mf_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_PostalCode_Description {
            get {
                return ResourceManager.GetString("Address_mf_PostalCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Code.
        /// </summary>
        internal static string Address_mf_RegionCode {
            get {
                return ResourceManager.GetString("Address_mf_RegionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_RegionCode_Description {
            get {
                return ResourceManager.GetString("Address_mf_RegionCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        internal static string Address_mf_RegionName {
            get {
                return ResourceManager.GetString("Address_mf_RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_RegionName_Description {
            get {
                return ResourceManager.GetString("Address_mf_RegionName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Address_mf_State {
            get {
                return ResourceManager.GetString("Address_mf_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Address_mf_State_Description {
            get {
                return ResourceManager.GetString("Address_mf_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has been deleted..
        /// </summary>
        internal static string Address_msg_Deleted {
            get {
                return ResourceManager.GetString("Address_msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address.
        /// </summary>
        internal static string Add_New_Address {
            get {
                return ResourceManager.GetString("Add_New_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contacts.
        /// </summary>
        internal static string AllContacts {
            get {
                return ResourceManager.GetString("AllContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AllCreditCard {
            get {
                return ResourceManager.GetString("AllCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All organizations.
        /// </summary>
        internal static string AllOrganizations {
            get {
                return ResourceManager.GetString("AllOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Role.
        /// </summary>
        internal static string AssignRole {
            get {
                return ResourceManager.GetString("AssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Password.
        /// </summary>
        internal static string ChangeUserPassword {
            get {
                return ResourceManager.GetString("ChangeUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        internal static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Organizations.
        /// </summary>
        internal static string ChildOrganizations {
            get {
                return ResourceManager.GetString("ChildOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Edit.
        /// </summary>
        internal static string ContactEdit {
            get {
                return ResourceManager.GetString("ContactEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact List.
        /// </summary>
        internal static string ContactList {
            get {
                return ResourceManager.GetString("ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact Note.
        /// </summary>
        internal static string ContactNoteNew {
            get {
                return ResourceManager.GetString("ContactNoteNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Notes.
        /// </summary>
        internal static string ContactNotes {
            get {
                return ResourceManager.GetString("ContactNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Note.
        /// </summary>
        internal static string ContactNote_mc {
            get {
                return ResourceManager.GetString("ContactNote_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactNote_mf_ContactId_Description {
            get {
                return ResourceManager.GetString("ContactNote_mf_ContactId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note content.
        /// </summary>
        internal static string ContactNote_mf_NoteContent_Description {
            get {
                return ResourceManager.GetString("ContactNote_mf_NoteContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note title.
        /// </summary>
        internal static string ContactNote_mf_NoteTitle_Description {
            get {
                return ResourceManager.GetString("ContactNote_mf_NoteTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact_mc {
            get {
                return ResourceManager.GetString("Contact_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string Contact_mf_BirthDate {
            get {
                return ResourceManager.GetString("Contact_mf_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_BirthDate_Description {
            get {
                return ResourceManager.GetString("Contact_mf_BirthDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Contact_mf_Code {
            get {
                return ResourceManager.GetString("Contact_mf_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_Code_Description {
            get {
                return ResourceManager.GetString("Contact_mf_Code_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Group.
        /// </summary>
        internal static string Contact_mf_CustomerGroup {
            get {
                return ResourceManager.GetString("Contact_mf_CustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_CustomerGroup_Description {
            get {
                return ResourceManager.GetString("Contact_mf_CustomerGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Contact_mf_Email {
            get {
                return ResourceManager.GetString("Contact_mf_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email Description.
        /// </summary>
        internal static string Contact_mf_Email_Description {
            get {
                return ResourceManager.GetString("Contact_mf_Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Contact_mf_FirstName {
            get {
                return ResourceManager.GetString("Contact_mf_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_FirstName_Description {
            get {
                return ResourceManager.GetString("Contact_mf_FirstName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Contact_mf_FullName {
            get {
                return ResourceManager.GetString("Contact_mf_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_FullName_Description {
            get {
                return ResourceManager.GetString("Contact_mf_FullName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Contact_mf_LastName {
            get {
                return ResourceManager.GetString("Contact_mf_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_LastName_Description {
            get {
                return ResourceManager.GetString("Contact_mf_LastName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Date.
        /// </summary>
        internal static string Contact_mf_LastOrder {
            get {
                return ResourceManager.GetString("Contact_mf_LastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_LastOrder_Description {
            get {
                return ResourceManager.GetString("Contact_mf_LastOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string Contact_mf_MiddleName {
            get {
                return ResourceManager.GetString("Contact_mf_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_MiddleName_Description {
            get {
                return ResourceManager.GetString("Contact_mf_MiddleName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Organization.
        /// </summary>
        internal static string Contact_mf_Owner {
            get {
                return ResourceManager.GetString("Contact_mf_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Organization.
        /// </summary>
        internal static string Contact_mf_OwnerId_Description {
            get {
                return ResourceManager.GetString("Contact_mf_OwnerId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_Owner_Description {
            get {
                return ResourceManager.GetString("Contact_mf_Owner_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Billing Address.
        /// </summary>
        internal static string Contact_mf_PreferredBillingAddress {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_PreferredBillingAddressId_Description {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredBillingAddressId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Currency.
        /// </summary>
        internal static string Contact_mf_PreferredCurrency {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_PreferredCurrency_Description {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredCurrency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        internal static string Contact_mf_PreferredLanguage {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_PreferredLanguage_Description {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Shipping Address.
        /// </summary>
        internal static string Contact_mf_PreferredShippingAddress {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_PreferredShippingAddressId_Description {
            get {
                return ResourceManager.GetString("Contact_mf_PreferredShippingAddressId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Source.
        /// </summary>
        internal static string Contact_mf_RegistrationSource {
            get {
                return ResourceManager.GetString("Contact_mf_RegistrationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Contact_mf_RegistrationSource_Description {
            get {
                return ResourceManager.GetString("Contact_mf_RegistrationSource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards.
        /// </summary>
        internal static string CreditCards {
            get {
                return ResourceManager.GetString("CreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards.
        /// </summary>
        internal static string CreditCards_mc {
            get {
                return ResourceManager.GetString("CreditCards_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCard_mc {
            get {
                return ResourceManager.GetString("CreditCard_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string CreditCard_mf_Address {
            get {
                return ResourceManager.GetString("CreditCard_mf_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditCard_mf_Address_Description {
            get {
                return ResourceManager.GetString("CreditCard_mf_Address_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CreditCard_mf_CardType {
            get {
                return ResourceManager.GetString("CreditCard_mf_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditCard_mf_CardType_Description {
            get {
                return ResourceManager.GetString("CreditCard_mf_CardType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string CreditCard_mf_Contact {
            get {
                return ResourceManager.GetString("CreditCard_mf_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CreditCard_mf_CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCard_mf_CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditCard_mf_CreditCardNumber_Description {
            get {
                return ResourceManager.GetString("CreditCard_mf_CreditCardNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month.
        /// </summary>
        internal static string CreditCard_mf_ExpirationMonth {
            get {
                return ResourceManager.GetString("CreditCard_mf_ExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditCard_mf_ExpirationMonth_Description {
            get {
                return ResourceManager.GetString("CreditCard_mf_ExpirationMonth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year.
        /// </summary>
        internal static string CreditCard_mf_ExpirationYear {
            get {
                return ResourceManager.GetString("CreditCard_mf_ExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditCard_mf_ExpirationYear_Description {
            get {
                return ResourceManager.GetString("CreditCard_mf_ExpirationYear_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Four Digits.
        /// </summary>
        internal static string CreditCard_mf_LastFourDigits {
            get {
                return ResourceManager.GetString("CreditCard_mf_LastFourDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditCard_mf_LastFourDigits_Description {
            get {
                return ResourceManager.GetString("CreditCard_mf_LastFourDigits_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string CreditCard_mf_Organization {
            get {
                return ResourceManager.GetString("CreditCard_mf_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        internal static string CreditCard_mf_SecurityCode {
            get {
                return ResourceManager.GetString("CreditCard_mf_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreditCard_mf_SecurityCode_Description {
            get {
                return ResourceManager.GetString("CreditCard_mf_SecurityCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Management.
        /// </summary>
        internal static string CustomerManagement {
            get {
                return ResourceManager.GetString("CustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        internal static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contact?.
        /// </summary>
        internal static string DeleteContactConfirmation {
            get {
                return ResourceManager.GetString("DeleteContactConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of selected Contact(s) is an organization&apos;s primary contact. Cannot delete Contact..
        /// </summary>
        internal static string DeleteContactIsOrganizationPrimary {
            get {
                return ResourceManager.GetString("DeleteContactIsOrganizationPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Organization, Child Organizations and Contacts..
        /// </summary>
        internal static string DeleteOrganizationAndContacts {
            get {
                return ResourceManager.GetString("DeleteOrganizationAndContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Organization Only..
        /// </summary>
        internal static string DeleteOrganizationOnly {
            get {
                return ResourceManager.GetString("DeleteOrganizationOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Organizations, Child Organizations and Contacts..
        /// </summary>
        internal static string DeleteOrganizationsAndContacts {
            get {
                return ResourceManager.GetString("DeleteOrganizationsAndContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Organizations Only..
        /// </summary>
        internal static string DeleteOrganizationsOnly {
            get {
                return ResourceManager.GetString("DeleteOrganizationsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Roles.
        /// </summary>
        internal static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCommerce.
        /// </summary>
        internal static string eCommerce {
            get {
                return ResourceManager.GetString("eCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role Assignment.
        /// </summary>
        internal static string EditRoleAssignment {
            get {
                return ResourceManager.GetString("EditRoleAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Editing.
        /// </summary>
        internal static string EditSystemView {
            get {
                return ResourceManager.GetString("EditSystemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary E-Mail Address.
        /// </summary>
        internal static string EMailAddress1 {
            get {
                return ResourceManager.GetString("EMailAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address 2.
        /// </summary>
        internal static string EMailAddress2 {
            get {
                return ResourceManager.GetString("EMailAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address 3.
        /// </summary>
        internal static string EMailAddress3 {
            get {
                return ResourceManager.GetString("EMailAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment Retail.
        /// </summary>
        internal static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Editing.
        /// </summary>
        internal static string EntityEdit {
            get {
                return ResourceManager.GetString("EntityEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        internal static string EntityList {
            get {
                return ResourceManager.GetString("EntityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Popup Edit.
        /// </summary>
        internal static string EntityPopupEdit {
            get {
                return ResourceManager.GetString("EntityPopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer View.
        /// </summary>
        internal static string EntityView {
            get {
                return ResourceManager.GetString("EntityView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to VCard.
        /// </summary>
        internal static string ExportVCF {
            get {
                return ResourceManager.GetString("ExportVCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        internal static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpPrefix.
        /// </summary>
        internal static string HelpPrefix {
            get {
                return ResourceManager.GetString("HelpPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Contacts.
        /// </summary>
        internal static string ImportContacts {
            get {
                return ResourceManager.GetString("ImportContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Organizations.
        /// </summary>
        internal static string ImportOrgs {
            get {
                return ResourceManager.GetString("ImportOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        internal static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1.
        /// </summary>
        internal static string Line1 {
            get {
                return ResourceManager.GetString("Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2.
        /// </summary>
        internal static string Line2 {
            get {
                return ResourceManager.GetString("Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 3.
        /// </summary>
        internal static string Line3 {
            get {
                return ResourceManager.GetString("Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        internal static string MembershipUser_Account_Not_Found {
            get {
                return ResourceManager.GetString("MembershipUser_Account_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Locked Out:.
        /// </summary>
        internal static string MembershipUser_IsLockedOut {
            get {
                return ResourceManager.GetString("MembershipUser_IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string MembershipUser_IsLockedOutFalse {
            get {
                return ResourceManager.GetString("MembershipUser_IsLockedOutFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string MembershipUser_IsLockedOutTrue {
            get {
                return ResourceManager.GetString("MembershipUser_IsLockedOutTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity:.
        /// </summary>
        internal static string MembershipUser_LastActivity {
            get {
                return ResourceManager.GetString("MembershipUser_LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Lockout:.
        /// </summary>
        internal static string MembershipUser_LastLockout {
            get {
                return ResourceManager.GetString("MembershipUser_LastLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login:.
        /// </summary>
        internal static string MembershipUser_LastLogin {
            get {
                return ResourceManager.GetString("MembershipUser_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Password Changed:.
        /// </summary>
        internal static string MembershipUser_LastPasswordChanged {
            get {
                return ResourceManager.GetString("MembershipUser_LastPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        internal static string NewContact {
            get {
                return ResourceManager.GetString("NewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Credit Card.
        /// </summary>
        internal static string NewCreditCard {
            get {
                return ResourceManager.GetString("NewCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Organization.
        /// </summary>
        internal static string NewOrganization {
            get {
                return ResourceManager.GetString("NewOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New View.
        /// </summary>
        internal static string NewSystemView {
            get {
                return ResourceManager.GetString("NewSystemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        internal static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-profit organizations.
        /// </summary>
        internal static string NonProfitOrg {
            get {
                return ResourceManager.GetString("NonProfitOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Content.
        /// </summary>
        internal static string NoteContent {
            get {
                return ResourceManager.GetString("NoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string NoteTitle {
            get {
                return ResourceManager.GetString("NoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Type.
        /// </summary>
        internal static string NoteType {
            get {
                return ResourceManager.GetString("NoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        internal static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Notes.
        /// </summary>
        internal static string OrderNotes {
            get {
                return ResourceManager.GetString("OrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization can have related contacts and child organizations. What do you want to delete?.
        /// </summary>
        internal static string OrganizationDeleteType {
            get {
                return ResourceManager.GetString("OrganizationDeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Edit.
        /// </summary>
        internal static string OrganizationEdit {
            get {
                return ResourceManager.GetString("OrganizationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string OrganizationEmpty {
            get {
                return ResourceManager.GetString("OrganizationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Info.
        /// </summary>
        internal static string OrganizationInfo {
            get {
                return ResourceManager.GetString("OrganizationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization List.
        /// </summary>
        internal static string OrganizationList {
            get {
                return ResourceManager.GetString("OrganizationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        internal static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected organizations can have related contacts and child organizations. What do you want to delete?.
        /// </summary>
        internal static string OrganizationsDeleteType {
            get {
                return ResourceManager.GetString("OrganizationsDeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string OrganizationUnit {
            get {
                return ResourceManager.GetString("OrganizationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Organization_mc {
            get {
                return ResourceManager.GetString("Organization_mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category.
        /// </summary>
        internal static string Organization_mf_BusinessCategory {
            get {
                return ResourceManager.GetString("Organization_mf_BusinessCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Organization_mf_BusinessCategory_Description {
            get {
                return ResourceManager.GetString("Organization_mf_BusinessCategory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Organization_mf_Description {
            get {
                return ResourceManager.GetString("Organization_mf_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Organization_mf_Description_Description {
            get {
                return ResourceManager.GetString("Organization_mf_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Organization_mf_Name {
            get {
                return ResourceManager.GetString("Organization_mf_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Organization_mf_Name_Description {
            get {
                return ResourceManager.GetString("Organization_mf_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Organization_mf_OrganizationType {
            get {
                return ResourceManager.GetString("Organization_mf_OrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Organization_mf_OrganizationType_Description {
            get {
                return ResourceManager.GetString("Organization_mf_OrganizationType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Customer Group.
        /// </summary>
        internal static string Organization_mf_OrgCustomerGroup {
            get {
                return ResourceManager.GetString("Organization_mf_OrgCustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Organization_mf_OrgCustomerGroup_Description {
            get {
                return ResourceManager.GetString("Organization_mf_OrgCustomerGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Organization.
        /// </summary>
        internal static string Organization_mf_Parent {
            get {
                return ResourceManager.GetString("Organization_mf_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Organization.
        /// </summary>
        internal static string Organization_mf_ParentId_Description {
            get {
                return ResourceManager.GetString("Organization_mf_ParentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Organization.
        /// </summary>
        internal static string Organization_mf_Parent_Description {
            get {
                return ResourceManager.GetString("Organization_mf_Parent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact.
        /// </summary>
        internal static string Organization_mf_PrimaryContact {
            get {
                return ResourceManager.GetString("Organization_mf_PrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Organization_mf_PrimaryContactId_Description {
            get {
                return ResourceManager.GetString("Organization_mf_PrimaryContactId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Office Box.
        /// </summary>
        internal static string PostOfficeBox {
            get {
                return ResourceManager.GetString("PostOfficeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact.
        /// </summary>
        internal static string PrimaryContact {
            get {
                return ResourceManager.GetString("PrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Objects.
        /// </summary>
        internal static string RelatedObjects {
            get {
                return ResourceManager.GetString("RelatedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Role Assignments.
        /// </summary>
        internal static string RoleAssignments {
            get {
                return ResourceManager.GetString("RoleAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritance.
        /// </summary>
        internal static string RoleAssignment_CheckMode {
            get {
                return ResourceManager.GetString("RoleAssignment_CheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Assignment Edit.
        /// </summary>
        internal static string RoleAssignment_Edit {
            get {
                return ResourceManager.GetString("RoleAssignment_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only For Owner.
        /// </summary>
        internal static string RoleAssignment_OnlyForOwner {
            get {
                return ResourceManager.GetString("RoleAssignment_OnlyForOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string RoleAssignment_OrganizationName {
            get {
                return ResourceManager.GetString("RoleAssignment_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string RoleAssignment_RoleName {
            get {
                return ResourceManager.GetString("RoleAssignment_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Edit.
        /// </summary>
        internal static string Role_Edit {
            get {
                return ResourceManager.GetString("Role_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role List.
        /// </summary>
        internal static string Role_List {
            get {
                return ResourceManager.GetString("Role_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string Role_Name {
            get {
                return ResourceManager.GetString("Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Billing Address.
        /// </summary>
        internal static string Same_As_Billing_Address {
            get {
                return ResourceManager.GetString("Same_As_Billing_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        internal static string SecurityCheckMode_AllowInheritRole {
            get {
                return ResourceManager.GetString("SecurityCheckMode_AllowInheritRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Inherited.
        /// </summary>
        internal static string SecurityCheckMode_DoNotAllowInheritRole {
            get {
                return ResourceManager.GetString("SecurityCheckMode_DoNotAllowInheritRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [undefined].
        /// </summary>
        internal static string SecurityCheckMode_Undefined {
            get {
                return ResourceManager.GetString("SecurityCheckMode_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        internal static string SecurityCheckMode_UnsetRole {
            get {
                return ResourceManager.GetString("SecurityCheckMode_UnsetRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Role.
        /// </summary>
        internal static string SecurityRole {
            get {
                return ResourceManager.GetString("SecurityRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contact.
        /// </summary>
        internal static string SelectContact {
            get {
                return ResourceManager.GetString("SelectContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Address.
        /// </summary>
        internal static string SetDefaultAddress {
            get {
                return ResourceManager.GetString("SetDefaultAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Primary Contact.
        /// </summary>
        internal static string SetPrimaryContact {
            get {
                return ResourceManager.GetString("SetPrimaryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Carts.
        /// </summary>
        internal static string ShoppingCarts {
            get {
                return ResourceManager.GetString("ShoppingCarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Lists.
        /// </summary>
        internal static string ShoppingLists {
            get {
                return ResourceManager.GetString("ShoppingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State sector.
        /// </summary>
        internal static string StateSector {
            get {
                return ResourceManager.GetString("StateSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TabDetails {
            get {
                return ResourceManager.GetString("TabDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TabGeneral {
            get {
                return ResourceManager.GetString("TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TabInfo {
            get {
                return ResourceManager.GetString("TabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Telephone.
        /// </summary>
        internal static string Telephone1 {
            get {
                return ResourceManager.GetString("Telephone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 2.
        /// </summary>
        internal static string Telephone2 {
            get {
                return ResourceManager.GetString("Telephone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 3.
        /// </summary>
        internal static string Telephone3 {
            get {
                return ResourceManager.GetString("Telephone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDos.
        /// </summary>
        internal static string ToDos {
            get {
                return ResourceManager.GetString("ToDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string UnlockUser {
            get {
                return ResourceManager.GetString("UnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Url.
        /// </summary>
        internal static string WebSiteUrl {
            get {
                return ResourceManager.GetString("WebSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish Lists.
        /// </summary>
        internal static string WishLists {
            get {
                return ResourceManager.GetString("WishLists", resourceCulture);
            }
        }
    }
}
