//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ReportingStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        internal static string Apply_Filter {
            get {
                return ResourceManager.GetString("Apply_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Sellers Report.
        /// </summary>
        internal static string Best_Sellers_Report {
            get {
                return ResourceManager.GetString("Best_Sellers_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers by Number of Orders Report.
        /// </summary>
        internal static string Customers_By_Number_Of_Orders_Report {
            get {
                return ResourceManager.GetString("Customers_By_Number_Of_Orders_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers by Orders Total Report.
        /// </summary>
        internal static string Customers_By_Orders_Total_Report {
            get {
                return ResourceManager.GetString("Customers_By_Orders_Total_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Stock Report.
        /// </summary>
        internal static string Low_Stock_Report {
            get {
                return ResourceManager.GetString("Low_Stock_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Report.
        /// </summary>
        internal static string Most_Viewed_Report {
            get {
                return ResourceManager.GetString("Most_Viewed_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Accounts Report.
        /// </summary>
        internal static string New_Accounts_Report {
            get {
                return ResourceManager.GetString("New_Accounts_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string Reporting {
            get {
                return ResourceManager.GetString("Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        internal static string Sales_Report {
            get {
                return ResourceManager.GetString("Sales_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Report.
        /// </summary>
        internal static string Shipping_Report {
            get {
                return ResourceManager.GetString("Shipping_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Report.
        /// </summary>
        internal static string Tax_Report {
            get {
                return ResourceManager.GetString("Tax_Report", resourceCulture);
            }
        }
    }
}
