//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sorting Set.
        /// </summary>
        internal static string AddSort {
            get {
                return ResourceManager.GetString("AddSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Filter.
        /// </summary>
        internal static string ChangeFilter {
            get {
                return ResourceManager.GetString("ChangeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to select.
        /// </summary>
        internal static string DoubleClick {
            get {
                return ResourceManager.GetString("DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string FieldsTab {
            get {
                return ResourceManager.GetString("FieldsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Is Not Set.
        /// </summary>
        internal static string FilterIsNotSet {
            get {
                return ResourceManager.GetString("FilterIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Is Set.
        /// </summary>
        internal static string FilterIsSet {
            get {
                return ResourceManager.GetString("FilterIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string FiltersTab {
            get {
                return ResourceManager.GetString("FiltersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to view.
        /// </summary>
        internal static string GoToViewLink {
            get {
                return ResourceManager.GetString("GoToViewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        internal static string GroupAdministrators {
            get {
                return ResourceManager.GetString("GroupAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string GroupEveryone {
            get {
                return ResourceManager.GetString("GroupEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Managers.
        /// </summary>
        internal static string GroupExec {
            get {
                return ResourceManager.GetString("GroupExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extranet.
        /// </summary>
        internal static string GroupExtranet {
            get {
                return ResourceManager.GetString("GroupExtranet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk Managers.
        /// </summary>
        internal static string GroupHDM {
            get {
                return ResourceManager.GetString("GroupHDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intranet.
        /// </summary>
        internal static string GroupIntranet {
            get {
                return ResourceManager.GetString("GroupIntranet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Managers.
        /// </summary>
        internal static string GroupPM {
            get {
                return ResourceManager.GetString("GroupPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Project Managers.
        /// </summary>
        internal static string GroupPPM {
            get {
                return ResourceManager.GetString("GroupPPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string GroupRoles {
            get {
                return ResourceManager.GetString("GroupRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string GroupsTab {
            get {
                return ResourceManager.GetString("GroupsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Managers.
        /// </summary>
        internal static string GroupTM {
            get {
                return ResourceManager.GetString("GroupTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this view for all users.
        /// </summary>
        internal static string IsPublicView {
            get {
                return ResourceManager.GetString("IsPublicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field was marked as unique! Enter another value please!.
        /// </summary>
        internal static string MustBeUnique {
            get {
                return ResourceManager.GetString("MustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is ready to create a new view for entities list. Please, type view name..
        /// </summary>
        internal static string NewViewGeneralTabComment {
            get {
                return ResourceManager.GetString("NewViewGeneralTabComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sorting sets.
        /// </summary>
        internal static string NoSortings {
            get {
                return ResourceManager.GetString("NoSortings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string principalDepartment {
            get {
                return ResourceManager.GetString("principalDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string principalEveryone {
            get {
                return ResourceManager.GetString("principalEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Company.
        /// </summary>
        internal static string principalMainCompany {
            get {
                return ResourceManager.GetString("principalMainCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Company.
        /// </summary>
        internal static string principalPartnerCompany {
            get {
                return ResourceManager.GetString("principalPartnerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string principalPartners {
            get {
                return ResourceManager.GetString("principalPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted.
        /// </summary>
        internal static string principalRestricted {
            get {
                return ResourceManager.GetString("principalRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string principalRole {
            get {
                return ResourceManager.GetString("principalRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string principalRoles {
            get {
                return ResourceManager.GetString("principalRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string principalTeam {
            get {
                return ResourceManager.GetString("principalTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string principalTeams {
            get {
                return ResourceManager.GetString("principalTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string principalUser {
            get {
                return ResourceManager.GetString("principalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Title.
        /// </summary>
        internal static string SelectTitle {
            get {
                return ResourceManager.GetString("SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display summary info.
        /// </summary>
        internal static string ShowGroupInfo {
            get {
                return ResourceManager.GetString("ShowGroupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Sets.
        /// </summary>
        internal static string SortingTitle {
            get {
                return ResourceManager.GetString("SortingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string tClose {
            get {
                return ResourceManager.GetString("tClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Is Required!.
        /// </summary>
        internal static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string tSave {
            get {
                return ResourceManager.GetString("tSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewFieldSet {
            get {
                return ResourceManager.GetString("ViewFieldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple template with one column.
        /// </summary>
        internal static string _mc_1Column_Description {
            get {
                return ResourceManager.GetString("_mc_1Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One column template.
        /// </summary>
        internal static string _mc_1Column_Name {
            get {
                return ResourceManager.GetString("_mc_1Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two columns template.
        /// </summary>
        internal static string _mc_1_1Column_Description {
            get {
                return ResourceManager.GetString("_mc_1_1Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default two columns template.
        /// </summary>
        internal static string _mc_1_1Column_Name {
            get {
                return ResourceManager.GetString("_mc_1_1Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three columns template.
        /// </summary>
        internal static string _mc_1_1_1Column_Description {
            get {
                return ResourceManager.GetString("_mc_1_1_1Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three columns template.
        /// </summary>
        internal static string _mc_1_1_1Column_Name {
            get {
                return ResourceManager.GetString("_mc_1_1_1Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two columns template.
        /// </summary>
        internal static string _mc_1_2Column_Description {
            get {
                return ResourceManager.GetString("_mc_1_2Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two column template (width 1 : 2).
        /// </summary>
        internal static string _mc_1_2Column_Name {
            get {
                return ResourceManager.GetString("_mc_1_2Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two columns template.
        /// </summary>
        internal static string _mc_2_1Column_Description {
            get {
                return ResourceManager.GetString("_mc_2_1Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two columns template (width 2 : 1).
        /// </summary>
        internal static string _mc_2_1Column_Name {
            get {
                return ResourceManager.GetString("_mc_2_1Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string _mc_Actions {
            get {
                return ResourceManager.GetString("_mc_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active&amp;nbsp;ToDo&amp;nbsp;List.
        /// </summary>
        internal static string _mc_ActiveActivities {
            get {
                return ResourceManager.GetString("_mc_ActiveActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_ActiveActivitiesDescription {
            get {
                return ResourceManager.GetString("_mc_ActiveActivitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active&amp;nbsp; Documents.
        /// </summary>
        internal static string _mc_ActiveDocuments {
            get {
                return ResourceManager.GetString("_mc_ActiveDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_ActiveDocumentsDescription {
            get {
                return ResourceManager.GetString("_mc_ActiveDocumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active&amp;nbsp; Projects.
        /// </summary>
        internal static string _mc_ActiveProjects {
            get {
                return ResourceManager.GetString("_mc_ActiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_ActiveProjectsDescription {
            get {
                return ResourceManager.GetString("_mc_ActiveProjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string _mc_Add {
            get {
                return ResourceManager.GetString("_mc_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the fields to add to the section..
        /// </summary>
        internal static string _mc_AddFieldsText {
            get {
                return ResourceManager.GetString("_mc_AddFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string _mc_All {
            get {
                return ResourceManager.GetString("_mc_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string _mc_Apply {
            get {
                return ResourceManager.GetString("_mc_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        internal static string _mc_BackToList {
            get {
                return ResourceManager.GetString("_mc_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom region.
        /// </summary>
        internal static string _mc_BottomRegion {
            get {
                return ResourceManager.GetString("_mc_BottomRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly&amp;nbsp;Calendar.
        /// </summary>
        internal static string _mc_Calendar {
            get {
                return ResourceManager.GetString("_mc_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_CalendarDescription {
            get {
                return ResourceManager.GetString("_mc_CalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _mc_Cancel {
            get {
                return ResourceManager.GetString("_mc_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Properties.
        /// </summary>
        internal static string _mc_ChangeProperties {
            get {
                return ResourceManager.GetString("_mc_ChangeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string _mc_Class {
            get {
                return ResourceManager.GetString("_mc_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column editor.
        /// </summary>
        internal static string _mc_ColumnEditor {
            get {
                return ResourceManager.GetString("_mc_ColumnEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Tasks.
        /// </summary>
        internal static string _mc_CommonTasks {
            get {
                return ResourceManager.GetString("_mc_CommonTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls settings.
        /// </summary>
        internal static string _mc_ControlsSettings {
            get {
                return ResourceManager.GetString("_mc_ControlsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show at page.
        /// </summary>
        internal static string _mc_ControlVisible {
            get {
                return ResourceManager.GetString("_mc_ControlVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string _mc_Delete {
            get {
                return ResourceManager.GetString("_mc_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to delete selected field?.
        /// </summary>
        internal static string _mc_DeleteFieldWarning {
            get {
                return ResourceManager.GetString("_mc_DeleteFieldWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to delete this form?.
        /// </summary>
        internal static string _mc_DeleteFormWarning {
            get {
                return ResourceManager.GetString("_mc_DeleteFormWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want to delete selected section?.
        /// </summary>
        internal static string _mc_DeleteSectionWarning {
            get {
                return ResourceManager.GetString("_mc_DeleteSectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteView.
        /// </summary>
        internal static string _mc_DeleteView {
            get {
                return ResourceManager.GetString("_mc_DeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this view?.
        /// </summary>
        internal static string _mc_DeleteViewWarning {
            get {
                return ResourceManager.GetString("_mc_DeleteViewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _mc_Department {
            get {
                return ResourceManager.GetString("_mc_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department List.
        /// </summary>
        internal static string _mc_DepartmentList {
            get {
                return ResourceManager.GetString("_mc_DepartmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department View.
        /// </summary>
        internal static string _mc_DepartmentView {
            get {
                return ResourceManager.GetString("_mc_DepartmentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _mc_Description {
            get {
                return ResourceManager.GetString("_mc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        internal static string _mc_Designer {
            get {
                return ResourceManager.GetString("_mc_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string _mc_Details {
            get {
                return ResourceManager.GetString("_mc_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display label on the form..
        /// </summary>
        internal static string _mc_DisplayLabel {
            get {
                return ResourceManager.GetString("_mc_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string _mc_Events {
            get {
                return ResourceManager.GetString("_mc_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My&amp;nbsp;favorite&amp;nbsp;lists.
        /// </summary>
        internal static string _mc_FavoriteLists {
            get {
                return ResourceManager.GetString("_mc_FavoriteLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_FavoriteListsDescription {
            get {
                return ResourceManager.GetString("_mc_FavoriteListsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string _mc_Field {
            get {
                return ResourceManager.GetString("_mc_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Field.
        /// </summary>
        internal static string _mc_FieldAdd {
            get {
                return ResourceManager.GetString("_mc_FieldAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the field for section..
        /// </summary>
        internal static string _mc_FieldAddText {
            get {
                return ResourceManager.GetString("_mc_FieldAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Properties.
        /// </summary>
        internal static string _mc_FieldProperties {
            get {
                return ResourceManager.GetString("_mc_FieldProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change field properties..
        /// </summary>
        internal static string _mc_FieldPropertiesText {
            get {
                return ResourceManager.GetString("_mc_FieldPropertiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Fields.
        /// </summary>
        internal static string _mc_FieldsAdd {
            get {
                return ResourceManager.GetString("_mc_FieldsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string _mc_Form {
            get {
                return ResourceManager.GetString("_mc_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Form.
        /// </summary>
        internal static string _mc_FormAdd {
            get {
                return ResourceManager.GetString("_mc_FormAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new form to the system..
        /// </summary>
        internal static string _mc_FormAddText {
            get {
                return ResourceManager.GetString("_mc_FormAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string _mc_Forms {
            get {
                return ResourceManager.GetString("_mc_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string _mc_General {
            get {
                return ResourceManager.GetString("_mc_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistants/Awareness&amp;nbsp;Tools.
        /// </summary>
        internal static string _mc_HelpInfo {
            get {
                return ResourceManager.GetString("_mc_HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_HelpInfoDescription {
            get {
                return ResourceManager.GetString("_mc_HelpInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string _mc_Horizontal {
            get {
                return ResourceManager.GetString("_mc_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have installed Internet Explorer 6 or lower,install Internet Explorer 7.0 or later version for correct work. You can download Internet Explorer 7.0 &lt;a href=&apos;http://www.microsoft.com/windows/downloads/ie/getitnow.mspx&apos;&gt;here&lt;/a&gt;..
        /// </summary>
        internal static string _mc_ie6update {
            get {
                return ResourceManager.GetString("_mc_ie6update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks-To-Dos&amp;nbsp;given&amp;nbsp;to&amp;nbsp;me.
        /// </summary>
        internal static string _mc_InActivities {
            get {
                return ResourceManager.GetString("_mc_InActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_InActivitiesDescription {
            get {
                return ResourceManager.GetString("_mc_InActivitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string _mc_Label {
            get {
                return ResourceManager.GetString("_mc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast&amp;nbsp;alert.
        /// </summary>
        internal static string _mc_LastAlert {
            get {
                return ResourceManager.GetString("_mc_LastAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_LastAlertDescription {
            get {
                return ResourceManager.GetString("_mc_LastAlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string _mc_Layout {
            get {
                return ResourceManager.GetString("_mc_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Column.
        /// </summary>
        internal static string _mc_LayoutOneColumn {
            get {
                return ResourceManager.GetString("_mc_LayoutOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Columns.
        /// </summary>
        internal static string _mc_LayoutTwoColumn {
            get {
                return ResourceManager.GetString("_mc_LayoutTwoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string _mc_Location {
            get {
                return ResourceManager.GetString("_mc_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Field.
        /// </summary>
        internal static string _mc_MetaField {
            get {
                return ResourceManager.GetString("_mc_MetaField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle left region.
        /// </summary>
        internal static string _mc_MLeftRegion {
            get {
                return ResourceManager.GetString("_mc_MLeftRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle right region.
        /// </summary>
        internal static string _mc_MRightRegion {
            get {
                return ResourceManager.GetString("_mc_MRightRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string _mc_New {
            get {
                return ResourceManager.GetString("_mc_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available items.
        /// </summary>
        internal static string _mc_NoGridData {
            get {
                return ResourceManager.GetString("_mc_NoGridData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string _mc_NoItems {
            get {
                return ResourceManager.GetString("_mc_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check one box or more.
        /// </summary>
        internal static string _mc_NoItemSelected {
            get {
                return ResourceManager.GetString("_mc_NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no selected items.
        /// </summary>
        internal static string _mc_NoSelectedItems {
            get {
                return ResourceManager.GetString("_mc_NoSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title.
        /// </summary>
        internal static string _mc_NoTitle {
            get {
                return ResourceManager.GetString("_mc_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        internal static string _mc_NotSet {
            get {
                return ResourceManager.GetString("_mc_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Forms.
        /// </summary>
        internal static string _mc_ObjectForms {
            get {
                return ResourceManager.GetString("_mc_ObjectForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks/To-Dos&amp;nbsp;given&amp;nbsp;by&amp;nbsp;me.
        /// </summary>
        internal static string _mc_OutActivities {
            get {
                return ResourceManager.GetString("_mc_OutActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_OutActivitiesDescription {
            get {
                return ResourceManager.GetString("_mc_OutActivitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        internal static string _mc_PageSize {
            get {
                return ResourceManager.GetString("_mc_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Title.
        /// </summary>
        internal static string _mc_ParentTitle {
            get {
                return ResourceManager.GetString("_mc_ParentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _mc_Print {
            get {
                return ResourceManager.GetString("_mc_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string _mc_Project {
            get {
                return ResourceManager.GetString("_mc_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make readonly on the form..
        /// </summary>
        internal static string _mc_ReadOnly {
            get {
                return ResourceManager.GetString("_mc_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  items.
        /// </summary>
        internal static string _mc_Records {
            get {
                return ResourceManager.GetString("_mc_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string _mc_Region {
            get {
                return ResourceManager.GetString("_mc_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string _mc_Remove {
            get {
                return ResourceManager.GetString("_mc_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove block from «My Work» page?.
        /// </summary>
        internal static string _mc_RemoveBlock {
            get {
                return ResourceManager.GetString("_mc_RemoveBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string _mc_Reset {
            get {
                return ResourceManager.GetString("_mc_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string _mc_Rows {
            get {
                return ResourceManager.GetString("_mc_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News&amp;nbsp;Channel.
        /// </summary>
        internal static string _mc_RssNews {
            get {
                return ResourceManager.GetString("_mc_RssNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _mc_RssNewsDescription {
            get {
                return ResourceManager.GetString("_mc_RssNewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _mc_Save {
            get {
                return ResourceManager.GetString("_mc_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string _mc_SaveChanges {
            get {
                return ResourceManager.GetString("_mc_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string _mc_Section {
            get {
                return ResourceManager.GetString("_mc_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Edit.
        /// </summary>
        internal static string _mc_SectionEdit {
            get {
                return ResourceManager.GetString("_mc_SectionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change section properties..
        /// </summary>
        internal static string _mc_SectionEditText {
            get {
                return ResourceManager.GetString("_mc_SectionEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Section.
        /// </summary>
        internal static string _mc_SectionNew {
            get {
                return ResourceManager.GetString("_mc_SectionNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new section to the tab..
        /// </summary>
        internal static string _mc_SectionNewText {
            get {
                return ResourceManager.GetString("_mc_SectionNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: %selCount%.
        /// </summary>
        internal static string _mc_Selected {
            get {
                return ResourceManager.GetString("_mc_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:.
        /// </summary>
        internal static string _mc_SelectedNoNumber {
            get {
                return ResourceManager.GetString("_mc_SelectedNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to default.
        /// </summary>
        internal static string _mc_SetDefault {
            get {
                return ResourceManager.GetString("_mc_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show border line for this section..
        /// </summary>
        internal static string _mc_ShowBorder {
            get {
                return ResourceManager.GetString("_mc_ShowBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the name of this section on the form..
        /// </summary>
        internal static string _mc_ShowName {
            get {
                return ResourceManager.GetString("_mc_ShowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string _mc_State {
            get {
                return ResourceManager.GetString("_mc_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string _mc_Tab {
            get {
                return ResourceManager.GetString("_mc_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Edit.
        /// </summary>
        internal static string _mc_TabEdit {
            get {
                return ResourceManager.GetString("_mc_TabEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit tab..
        /// </summary>
        internal static string _mc_TabEditText {
            get {
                return ResourceManager.GetString("_mc_TabEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        internal static string _mc_TabNew {
            get {
                return ResourceManager.GetString("_mc_TabNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new tab to the form..
        /// </summary>
        internal static string _mc_TabNewText {
            get {
                return ResourceManager.GetString("_mc_TabNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template settings.
        /// </summary>
        internal static string _mc_TemplateSettings {
            get {
                return ResourceManager.GetString("_mc_TemplateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Management.
        /// </summary>
        internal static string _mc_TimeManagement {
            get {
                return ResourceManager.GetString("_mc_TimeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period.
        /// </summary>
        internal static string _mc_TimePeriod {
            get {
                return ResourceManager.GetString("_mc_TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string _mc_Title {
            get {
                return ResourceManager.GetString("_mc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title has already used!.
        /// </summary>
        internal static string _mc_TitleExistsError {
            get {
                return ResourceManager.GetString("_mc_TitleExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is not entered.
        /// </summary>
        internal static string _mc_TitleIsNotEntered {
            get {
                return ResourceManager.GetString("_mc_TitleIsNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top region.
        /// </summary>
        internal static string _mc_TopRegion {
            get {
                return ResourceManager.GetString("_mc_TopRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string _mc_Total {
            get {
                return ResourceManager.GetString("_mc_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _mc_Type {
            get {
                return ResourceManager.GetString("_mc_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string _mc_User {
            get {
                return ResourceManager.GetString("_mc_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string _mc_UserList {
            get {
                return ResourceManager.GetString("_mc_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string _mc_Vertical {
            get {
                return ResourceManager.GetString("_mc_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workgroups.
        /// </summary>
        internal static string _mc_WorkgroupList {
            get {
                return ResourceManager.GetString("_mc_WorkgroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workgroup View.
        /// </summary>
        internal static string _mc_WorkgroupView {
            get {
                return ResourceManager.GetString("_mc_WorkgroupView", resourceCulture);
            }
        }
    }
}
