//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalFieldManageControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalFieldManageControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalFieldManageControls", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Negative Values.
        /// </summary>
        internal static string AllowNegativeValues {
            get {
                return ResourceManager.GetString("AllowNegativeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox Label.
        /// </summary>
        internal static string CheckBoxLabel {
            get {
                return ResourceManager.GetString("CheckBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked by Default.
        /// </summary>
        internal static string CheckedByDefault {
            get {
                return ResourceManager.GetString("CheckedByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date As Default.
        /// </summary>
        internal static string CurrentDateAsDefault {
            get {
                return ResourceManager.GetString("CurrentDateAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Values.
        /// </summary>
        internal static string DefaultValues {
            get {
                return ResourceManager.GetString("DefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Dictionary.
        /// </summary>
        internal static string EditableDictionary {
            get {
                return ResourceManager.GetString("EditableDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        internal static string FriendlyName {
            get {
                return ResourceManager.GetString("FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length.
        /// </summary>
        internal static string MaximumLength {
            get {
                return ResourceManager.GetString("MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Value.
        /// </summary>
        internal static string MaximumValue {
            get {
                return ResourceManager.GetString("MaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Value.
        /// </summary>
        internal static string MinimumValue {
            get {
                return ResourceManager.GetString("MinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Default Value.
        /// </summary>
        internal static string NoDefaultValue {
            get {
                return ResourceManager.GetString("NoDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No&quot; text.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ No value ].
        /// </summary>
        internal static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the dictionary public.
        /// </summary>
        internal static string PublicDictionary {
            get {
                return ResourceManager.GetString("PublicDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string ReferencedClass {
            get {
                return ResourceManager.GetString("ReferencedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string ReferencedField {
            get {
                return ResourceManager.GetString("ReferencedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Pattern.
        /// </summary>
        internal static string RegexPattern {
            get {
                return ResourceManager.GetString("RegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Border.
        /// </summary>
        internal static string ShowBorder {
            get {
                return ResourceManager.GetString("ShowBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string tName {
            get {
                return ResourceManager.GetString("tName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique value.
        /// </summary>
        internal static string UniqueValue {
            get {
                return ResourceManager.GetString("UniqueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Roles of the Referenced Table.
        /// </summary>
        internal static string UseObjectRoles {
            get {
                return ResourceManager.GetString("UseObjectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Time Offset.
        /// </summary>
        internal static string UseTimeOffset {
            get {
                return ResourceManager.GetString("UseTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Yes&quot; text.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
