//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalMetaInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMetaInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalMetaInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child Item.
        /// </summary>
        internal static string AddChildItem {
            get {
                return ResourceManager.GetString("AddChildItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Inner Item.
        /// </summary>
        internal static string AddInnerItem {
            get {
                return ResourceManager.GetString("AddInnerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add System View.
        /// </summary>
        internal static string AddSystemView {
            get {
                return ResourceManager.GetString("AddSystemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Field To.
        /// </summary>
        internal static string AddToForm {
            get {
                return ResourceManager.GetString("AddToForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation.
        /// </summary>
        internal static string Aggregation {
            get {
                return ResourceManager.GetString("Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Transitions.
        /// </summary>
        internal static string AllowedTransitions {
            get {
                return ResourceManager.GetString("AllowedTransitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Nulls.
        /// </summary>
        internal static string AllowNulls {
            get {
                return ResourceManager.GetString("AllowNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        internal static string AscSort {
            get {
                return ResourceManager.GetString("AscSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments Types.
        /// </summary>
        internal static string AssignTypes {
            get {
                return ResourceManager.GetString("AssignTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available columns.
        /// </summary>
        internal static string AvailableColumns {
            get {
                return ResourceManager.GetString("AvailableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available States.
        /// </summary>
        internal static string AvailableStates {
            get {
                return ResourceManager.GetString("AvailableStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackReference.
        /// </summary>
        internal static string BackReference {
            get {
                return ResourceManager.GetString("BackReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Enum Info.
        /// </summary>
        internal static string BackToEnumInfo {
            get {
                return ResourceManager.GetString("BackToEnumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackToTableInfo {
            get {
                return ResourceManager.GetString("BackToTableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string BafExport {
            get {
                return ResourceManager.GetString("BafExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string BafImport {
            get {
                return ResourceManager.GetString("BafImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is between.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        internal static string Bridge {
            get {
                return ResourceManager.GetString("Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bridge.
        /// </summary>
        internal static string BridgeCreate {
            get {
                return ResourceManager.GetString("BridgeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Customization.
        /// </summary>
        internal static string BridgeCustomization {
            get {
                return ResourceManager.GetString("BridgeCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Edit.
        /// </summary>
        internal static string BridgeEdit {
            get {
                return ResourceManager.GetString("BridgeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation with  system name {0} already exists. Try another relation system name..
        /// </summary>
        internal static string BridgeExistsErrorMessage {
            get {
                return ResourceManager.GetString("BridgeExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object Extension.
        /// </summary>
        internal static string BusinessObjectExtension {
            get {
                return ResourceManager.GetString("BusinessObjectExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Business Objects ].
        /// </summary>
        internal static string BusinessObjectsBlock {
            get {
                return ResourceManager.GetString("BusinessObjectsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Extension.
        /// </summary>
        internal static string CardCreate {
            get {
                return ResourceManager.GetString("CardCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object Extension Customization.
        /// </summary>
        internal static string CardCustomization {
            get {
                return ResourceManager.GetString("CardCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Extension.
        /// </summary>
        internal static string CardEdit {
            get {
                return ResourceManager.GetString("CardEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension with system name {0} already exists. Try other Extension system name..
        /// </summary>
        internal static string CardExistsErrorMessage {
            get {
                return ResourceManager.GetString("CardExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckboxBoolean.
        /// </summary>
        internal static string CheckboxBoolean {
            get {
                return ResourceManager.GetString("CheckboxBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Script.
        /// </summary>
        internal static string ClientScript {
            get {
                return ResourceManager.GetString("ClientScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        internal static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Length.
        /// </summary>
        internal static string CounterLength {
            get {
                return ResourceManager.GetString("CounterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Reset.
        /// </summary>
        internal static string CounterReset {
            get {
                return ResourceManager.GetString("CounterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day.
        /// </summary>
        internal static string CounterResetDay {
            get {
                return ResourceManager.GetString("CounterResetDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Month.
        /// </summary>
        internal static string CounterResetMonth {
            get {
                return ResourceManager.GetString("CounterResetMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Never ].
        /// </summary>
        internal static string CounterResetNone {
            get {
                return ResourceManager.GetString("CounterResetNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Quarter.
        /// </summary>
        internal static string CounterResetQuarter {
            get {
                return ResourceManager.GetString("CounterResetQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Year.
        /// </summary>
        internal static string CounterResetYear {
            get {
                return ResourceManager.GetString("CounterResetYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Business Object.
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Object.
        /// </summary>
        internal static string CurrentObject {
            get {
                return ResourceManager.GetString("CurrentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Page.
        /// </summary>
        internal static string CustomPage {
            get {
                return ResourceManager.GetString("CustomPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom sorting.
        /// </summary>
        internal static string CustomSorting {
            get {
                return ResourceManager.GetString("CustomSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal percent.
        /// </summary>
        internal static string DecimalPercent {
            get {
                return ResourceManager.GetString("DecimalPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        internal static string DescSort {
            get {
                return ResourceManager.GetString("DescSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details type.
        /// </summary>
        internal static string DetailsType {
            get {
                return ResourceManager.GetString("DetailsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Region.
        /// </summary>
        internal static string DisplayRegion {
            get {
                return ResourceManager.GetString("DisplayRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Text.
        /// </summary>
        internal static string DisplayText {
            get {
                return ResourceManager.GetString("DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDownBoolean.
        /// </summary>
        internal static string DropDownBoolean {
            get {
                return ResourceManager.GetString("DropDownBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit columns.
        /// </summary>
        internal static string EditColumns {
            get {
                return ResourceManager.GetString("EditColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Dictionary.
        /// </summary>
        internal static string EditDictionary {
            get {
                return ResourceManager.GetString("EditDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Field.
        /// </summary>
        internal static string EditField {
            get {
                return ResourceManager.GetString("EditField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page.
        /// </summary>
        internal static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Realtion &quot;one to many&quot;.
        /// </summary>
        internal static string EditRelation1N {
            get {
                return ResourceManager.GetString("EditRelation1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Realtion &quot;many to one&quot;.
        /// </summary>
        internal static string EditRelationN1 {
            get {
                return ResourceManager.GetString("EditRelationN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Realtion &quot;many to many&quot;.
        /// </summary>
        internal static string EditRelationNN {
            get {
                return ResourceManager.GetString("EditRelationNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Business Object.
        /// </summary>
        internal static string EditTable {
            get {
                return ResourceManager.GetString("EditTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string EditType {
            get {
                return ResourceManager.GetString("EditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Type.
        /// </summary>
        internal static string ElementType {
            get {
                return ResourceManager.GetString("ElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable client sorting.
        /// </summary>
        internal static string EnableClientSort {
            get {
                return ResourceManager.GetString("EnableClientSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable columns drag&apos;n&apos;drop.
        /// </summary>
        internal static string EnableColumnDrag {
            get {
                return ResourceManager.GetString("EnableColumnDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Enum.
        /// </summary>
        internal static string EnumCreate {
            get {
                return ResourceManager.GetString("EnumCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum Edit.
        /// </summary>
        internal static string EnumEdit {
            get {
                return ResourceManager.GetString("EnumEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage List.
        /// </summary>
        internal static string EnumInfo {
            get {
                return ResourceManager.GetString("EnumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum List.
        /// </summary>
        internal static string EnumList {
            get {
                return ResourceManager.GetString("EnumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should check Allow Nulls or specify Default Value.
        /// </summary>
        internal static string ErrorMessage_AllowNulls {
            get {
                return ResourceManager.GetString("ErrorMessage_AllowNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field 1 Info.
        /// </summary>
        internal static string Field1Info {
            get {
                return ResourceManager.GetString("Field1Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field 2 Info.
        /// </summary>
        internal static string Field2Info {
            get {
                return ResourceManager.GetString("Field2Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with  system name {0} already exists. Try another system name..
        /// </summary>
        internal static string FieldExistsErrorMessage {
            get {
                return ResourceManager.GetString("FieldExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Info.
        /// </summary>
        internal static string FieldInfo {
            get {
                return ResourceManager.GetString("FieldInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Type.
        /// </summary>
        internal static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float percent.
        /// </summary>
        internal static string FloatPercent {
            get {
                return ResourceManager.GetString("FloatPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FormType {
            get {
                return ResourceManager.GetString("FormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        internal static string FriendlyName {
            get {
                return ResourceManager.GetString("FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From State.
        /// </summary>
        internal static string FromState {
            get {
                return ResourceManager.GetString("FromState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        internal static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General View.
        /// </summary>
        internal static string GeneralView {
            get {
                return ResourceManager.GetString("GeneralView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        internal static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        internal static string GreaterOrEqual {
            get {
                return ResourceManager.GetString("GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        internal static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier List.
        /// </summary>
        internal static string IdentifierList {
            get {
                return ResourceManager.GetString("IdentifierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        internal static string IdentifierMask {
            get {
                return ResourceManager.GetString("IdentifierMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier Name.
        /// </summary>
        internal static string IdentifierName {
            get {
                return ResourceManager.GetString("IdentifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string IdentifierScope {
            get {
                return ResourceManager.GetString("IdentifierScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is any of.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object Customization.
        /// </summary>
        internal static string InfoCustomization {
            get {
                return ResourceManager.GetString("InfoCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer percent.
        /// </summary>
        internal static string IntegerPercent {
            get {
                return ResourceManager.GetString("IntegerPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is false.
        /// </summary>
        internal static string IsFalse {
            get {
                return ResourceManager.GetString("IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        internal static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is true.
        /// </summary>
        internal static string IsTrue {
            get {
                return ResourceManager.GetString("IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Value.
        /// </summary>
        internal static string ItemDisplayValue {
            get {
                return ResourceManager.GetString("ItemDisplayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; nothing is selected &gt;.
        /// </summary>
        internal static string ItemNotSelected {
            get {
                return ResourceManager.GetString("ItemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Value.
        /// </summary>
        internal static string ItemValue {
            get {
                return ResourceManager.GetString("ItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only latin characters, numbers and the underscore are acceptable..
        /// </summary>
        internal static string LatinOnlyError {
            get {
                return ResourceManager.GetString("LatinOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        internal static string LessOrEqual {
            get {
                return ResourceManager.GetString("LessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is like.
        /// </summary>
        internal static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Page.
        /// </summary>
        internal static string ListPage {
            get {
                return ResourceManager.GetString("ListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string ListType {
            get {
                return ResourceManager.GetString("ListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongText.
        /// </summary>
        internal static string LongText {
            get {
                return ResourceManager.GetString("LongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #:Counter, YYYY:Year, MM:Month, DD:Day, QQ:Quarter.
        /// </summary>
        internal static string MaskTooltip {
            get {
                return ResourceManager.GetString("MaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length.
        /// </summary>
        internal static string MaximumLength {
            get {
                return ResourceManager.GetString("MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation.
        /// </summary>
        internal static string McDataType_Aggregation {
            get {
                return ResourceManager.GetString("McDataType_Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Reference.
        /// </summary>
        internal static string McDataType_BackReference {
            get {
                return ResourceManager.GetString("McDataType_BackReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string McDataType_Boolean {
            get {
                return ResourceManager.GetString("McDataType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string McDataType_Card {
            get {
                return ResourceManager.GetString("McDataType_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string McDataType_Complex {
            get {
                return ResourceManager.GetString("McDataType_Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string McDataType_Currency {
            get {
                return ResourceManager.GetString("McDataType_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string McDataType_DateTime {
            get {
                return ResourceManager.GetString("McDataType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string McDataType_Decimal {
            get {
                return ResourceManager.GetString("McDataType_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string McDataType_Double {
            get {
                return ResourceManager.GetString("McDataType_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary items.
        /// </summary>
        internal static string McDataType_Enum {
            get {
                return ResourceManager.GetString("McDataType_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string McDataType_File {
            get {
                return ResourceManager.GetString("McDataType_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string McDataType_Guid {
            get {
                return ResourceManager.GetString("McDataType_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string McDataType_Identifier {
            get {
                return ResourceManager.GetString("McDataType_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string McDataType_Integer {
            get {
                return ResourceManager.GetString("McDataType_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string McDataType_Link {
            get {
                return ResourceManager.GetString("McDataType_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Reference.
        /// </summary>
        internal static string McDataType_MultiReference {
            get {
                return ResourceManager.GetString("McDataType_MultiReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string McDataType_Reference {
            get {
                return ResourceManager.GetString("McDataType_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced Field (read-only).
        /// </summary>
        internal static string McDataType_ReferencedField {
            get {
                return ResourceManager.GetString("McDataType_ReferencedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string McDataType_String {
            get {
                return ResourceManager.GetString("McDataType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Icon.
        /// </summary>
        internal static string MenuItemIcon {
            get {
                return ResourceManager.GetString("MenuItemIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Link.
        /// </summary>
        internal static string MenuItemLink {
            get {
                return ResourceManager.GetString("MenuItemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Text.
        /// </summary>
        internal static string MenuItemText {
            get {
                return ResourceManager.GetString("MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section/Delimeter.
        /// </summary>
        internal static string MenuSection {
            get {
                return ResourceManager.GetString("MenuSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables List.
        /// </summary>
        internal static string MetaClassList {
            get {
                return ResourceManager.GetString("MetaClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaClass name.
        /// </summary>
        internal static string MetaClassName {
            get {
                return ResourceManager.GetString("MetaClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference MetaClasses.
        /// </summary>
        internal static string MReferenceMetaClasses {
            get {
                return ResourceManager.GetString("MReferenceMetaClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New MultiReference Type.
        /// </summary>
        internal static string MReferenceTypeCreate {
            get {
                return ResourceManager.GetString("MReferenceTypeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit MultiReference Type.
        /// </summary>
        internal static string MReferenceTypeEdit {
            get {
                return ResourceManager.GetString("MReferenceTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiReference Type Info.
        /// </summary>
        internal static string MReferenceTypeInfo {
            get {
                return ResourceManager.GetString("MReferenceTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiReference Type List.
        /// </summary>
        internal static string MReferenceTypeList {
            get {
                return ResourceManager.GetString("MReferenceTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Value.
        /// </summary>
        internal static string MultiValue {
            get {
                return ResourceManager.GetString("MultiValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bridge.
        /// </summary>
        internal static string NewBridge {
            get {
                return ResourceManager.GetString("NewBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Extension.
        /// </summary>
        internal static string NewCard {
            get {
                return ResourceManager.GetString("NewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Extension.
        /// </summary>
        internal static string NewCard2 {
            get {
                return ResourceManager.GetString("NewCard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Field.
        /// </summary>
        internal static string NewField {
            get {
                return ResourceManager.GetString("NewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Identifier.
        /// </summary>
        internal static string NewIdentifier {
            get {
                return ResourceManager.GetString("NewIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Business Object.
        /// </summary>
        internal static string NewInfoTable {
            get {
                return ResourceManager.GetString("NewInfoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Link.
        /// </summary>
        internal static string NewLink {
            get {
                return ResourceManager.GetString("NewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New - Multi Value.
        /// </summary>
        internal static string NewMultiValue {
            get {
                return ResourceManager.GetString("NewMultiValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Relation &quot;one to many&quot;.
        /// </summary>
        internal static string NewRelation1N {
            get {
                return ResourceManager.GetString("NewRelation1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Relation &quot;many to one&quot;.
        /// </summary>
        internal static string NewRelationN1 {
            get {
                return ResourceManager.GetString("NewRelationN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Relation &quot;many to many&quot;.
        /// </summary>
        internal static string NewRelationNN {
            get {
                return ResourceManager.GetString("NewRelationNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New - Single Value.
        /// </summary>
        internal static string NewSingleValue {
            get {
                return ResourceManager.GetString("NewSingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New System View.
        /// </summary>
        internal static string NewSystemView {
            get {
                return ResourceManager.GetString("NewSystemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New View.
        /// </summary>
        internal static string NewView {
            get {
                return ResourceManager.GetString("NewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        internal static string NotContains {
            get {
                return ResourceManager.GetString("NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not equal.
        /// </summary>
        internal static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is none of.
        /// </summary>
        internal static string NotIn {
            get {
                return ResourceManager.GetString("NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not like.
        /// </summary>
        internal static string NotLike {
            get {
                return ResourceManager.GetString("NotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Not Set ].
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Object Id.
        /// </summary>
        internal static string ObjectId {
            get {
                return ResourceManager.GetString("ObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        internal static string ObjectNotSet {
            get {
                return ResourceManager.GetString("ObjectNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size:.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string PageSize10 {
            get {
                return ResourceManager.GetString("PageSize10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string PageSize100 {
            get {
                return ResourceManager.GetString("PageSize100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string PageSize25 {
            get {
                return ResourceManager.GetString("PageSize25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string PageSize50 {
            get {
                return ResourceManager.GetString("PageSize50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string PageSizeAll {
            get {
                return ResourceManager.GetString("PageSizeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Business Object.
        /// </summary>
        internal static string ParentTable {
            get {
                return ResourceManager.GetString("ParentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural Name.
        /// </summary>
        internal static string PluralName {
            get {
                return ResourceManager.GetString("PluralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string PrimaryKeyId {
            get {
                return ResourceManager.GetString("PrimaryKeyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Object.
        /// </summary>
        internal static string PrimaryObject {
            get {
                return ResourceManager.GetString("PrimaryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User/Group.
        /// </summary>
        internal static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and Groups.
        /// </summary>
        internal static string Principals {
            get {
                return ResourceManager.GetString("Principals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        internal static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferencedField.
        /// </summary>
        internal static string ReferencedField {
            get {
                return ResourceManager.GetString("ReferencedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Object.
        /// </summary>
        internal static string RelatedObject {
            get {
                return ResourceManager.GetString("RelatedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation 1:N.
        /// </summary>
        internal static string Relation1N {
            get {
                return ResourceManager.GetString("Relation1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation N:1.
        /// </summary>
        internal static string RelationN1 {
            get {
                return ResourceManager.GetString("RelationN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Name.
        /// </summary>
        internal static string RelationName {
            get {
                return ResourceManager.GetString("RelationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation N:N.
        /// </summary>
        internal static string RelationNN {
            get {
                return ResourceManager.GetString("RelationNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:N Relations.
        /// </summary>
        internal static string Relations1N {
            get {
                return ResourceManager.GetString("Relations1N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:1 Relations.
        /// </summary>
        internal static string RelationsN1 {
            get {
                return ResourceManager.GetString("RelationsN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:N Relations.
        /// </summary>
        internal static string RelationsNN {
            get {
                return ResourceManager.GetString("RelationsNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset To Default.
        /// </summary>
        internal static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following syntax to get the values from the resource file: {ResourceName:ResourceKey}.
        /// </summary>
        internal static string ResourceTooltip {
            get {
                return ResourceManager.GetString("ResourceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User / Group.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users / Groups.
        /// </summary>
        internal static string RoleMultiValue {
            get {
                return ResourceManager.GetString("RoleMultiValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object.
        /// </summary>
        internal static string ScopeClass {
            get {
                return ResourceManager.GetString("ScopeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string ScopeField {
            get {
                return ResourceManager.GetString("ScopeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string ScopeGlobal {
            get {
                return ResourceManager.GetString("ScopeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string SecurityPage {
            get {
                return ResourceManager.GetString("SecurityPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Objects Security.
        /// </summary>
        internal static string SecurityTemplates {
            get {
                return ResourceManager.GetString("SecurityTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected States.
        /// </summary>
        internal static string SelectedStates {
            get {
                return ResourceManager.GetString("SelectedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        internal static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filters.
        /// </summary>
        internal static string ShowFilters {
            get {
                return ResourceManager.GetString("ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show groups.
        /// </summary>
        internal static string ShowGroups {
            get {
                return ResourceManager.GetString("ShowGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Value.
        /// </summary>
        internal static string SingleValue {
            get {
                return ResourceManager.GetString("SingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State List.
        /// </summary>
        internal static string StateList {
            get {
                return ResourceManager.GetString("StateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine.
        /// </summary>
        internal static string StateMachine {
            get {
                return ResourceManager.GetString("StateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machines.
        /// </summary>
        internal static string StateMachineList {
            get {
                return ResourceManager.GetString("StateMachineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StateMachineName {
            get {
                return ResourceManager.GetString("StateMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Extensions.
        /// </summary>
        internal static string SupportsCards {
            get {
                return ResourceManager.GetString("SupportsCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        internal static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System View.
        /// </summary>
        internal static string SystemView {
            get {
                return ResourceManager.GetString("SystemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System View Editing.
        /// </summary>
        internal static string SystemViewEditing {
            get {
                return ResourceManager.GetString("SystemViewEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Views.
        /// </summary>
        internal static string SystemViews {
            get {
                return ResourceManager.GetString("SystemViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object with system name {0} already exists. Try other Business Object system name..
        /// </summary>
        internal static string TableExistsErrorMessage {
            get {
                return ResourceManager.GetString("TableExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Info.
        /// </summary>
        internal static string TableInfo {
            get {
                return ResourceManager.GetString("TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object Name.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Business Object.
        /// </summary>
        internal static string TableOwner {
            get {
                return ResourceManager.GetString("TableOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        internal static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export/Import.
        /// </summary>
        internal static string ToolBarMenuBafExportImport {
            get {
                return ResourceManager.GetString("ToolBarMenuBafExportImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string ToolBarMenuBafNewItem {
            get {
                return ResourceManager.GetString("ToolBarMenuBafNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To State.
        /// </summary>
        internal static string ToState {
            get {
                return ResourceManager.GetString("ToState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Name.
        /// </summary>
        internal static string TransitionName {
            get {
                return ResourceManager.GetString("TransitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string TriggerAction {
            get {
                return ResourceManager.GetString("TriggerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string TriggerCondition {
            get {
                return ResourceManager.GetString("TriggerCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User views.
        /// </summary>
        internal static string UserViews {
            get {
                return ResourceManager.GetString("UserViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Editing.
        /// </summary>
        internal static string ViewEditing {
            get {
                return ResourceManager.GetString("ViewEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Page.
        /// </summary>
        internal static string ViewPage {
            get {
                return ResourceManager.GetString("ViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        internal static string ViewType {
            get {
                return ResourceManager.GetString("ViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible columns.
        /// </summary>
        internal static string VisibleColumns {
            get {
                return ResourceManager.GetString("VisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this file?.
        /// </summary>
        internal static string WarningFile {
            get {
                return ResourceManager.GetString("WarningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
