//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CoreStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency that will be used is cases where currency is needed but not specified.
        /// </summary>
        internal static string CommonSettings_Currency_Description {
            get {
                return ResourceManager.GetString("CommonSettings_Currency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language that will be selected by default in drowdowns, etc..
        /// </summary>
        internal static string CommonSettings_Language_Description {
            get {
                return ResourceManager.GetString("CommonSettings_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default unit of length.
        /// </summary>
        internal static string CommonSettings_Length_Unit_Description {
            get {
                return ResourceManager.GetString("CommonSettings_Length_Unit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default unit of weight.
        /// </summary>
        internal static string CommonSettings_Weight_Unit_Description {
            get {
                return ResourceManager.GetString("CommonSettings_Weight_Unit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Controls.
        /// </summary>
        internal static string Config_Replication_Controls {
            get {
                return ResourceManager.GetString("Config_Replication_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom1 Cycle.
        /// </summary>
        internal static string Cycle_Custom1 {
            get {
                return ResourceManager.GetString("Cycle_Custom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom2 Cycle.
        /// </summary>
        internal static string Cycle_Custom2 {
            get {
                return ResourceManager.GetString("Cycle_Custom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Cycle.
        /// </summary>
        internal static string Cycle_Daily {
            get {
                return ResourceManager.GetString("Cycle_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Cycle.
        /// </summary>
        internal static string Cycle_Monthly {
            get {
                return ResourceManager.GetString("Cycle_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cycle.
        /// </summary>
        internal static string Cycle_No {
            get {
                return ResourceManager.GetString("Cycle_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Cycle.
        /// </summary>
        internal static string Cycle_Weekly {
            get {
                return ResourceManager.GetString("Cycle_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Cycle.
        /// </summary>
        internal static string Cycle_Yearly {
            get {
                return ResourceManager.GetString("Cycle_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Line Items.
        /// </summary>
        internal static string DialogControl_Select_Line_Items {
            get {
                return ResourceManager.GetString("DialogControl_Select_Line_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string License_Activated {
            get {
                return ResourceManager.GetString("License_Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string License_Component {
            get {
                return ResourceManager.GetString("License_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string License_Edition {
            get {
                return ResourceManager.GetString("License_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        internal static string License_Expires {
            get {
                return ResourceManager.GetString("License_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Installation.
        /// </summary>
        internal static string License_Installation {
            get {
                return ResourceManager.GetString("License_Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install by License Key.
        /// </summary>
        internal static string License_Install_By_Key {
            get {
                return ResourceManager.GetString("License_Install_By_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install License File (*.lic).
        /// </summary>
        internal static string License_Install_File {
            get {
                return ResourceManager.GetString("License_Install_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed to.
        /// </summary>
        internal static string License_Licensed_To {
            get {
                return ResourceManager.GetString("License_Licensed_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Logs Export.
        /// </summary>
        internal static string LogExport_All_Logs_Export {
            get {
                return ResourceManager.GetString("LogExport_All_Logs_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page Logs Export.
        /// </summary>
        internal static string LogExport_Current_Page_Logs_Export {
            get {
                return ResourceManager.GetString("LogExport_Current_Page_Logs_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Logs Export.
        /// </summary>
        internal static string LogExport_View_Logs_Export {
            get {
                return ResourceManager.GetString("LogExport_View_Logs_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Binary Value].
        /// </summary>
        internal static string MetaDataView_BinaryValue {
            get {
                return ResourceManager.GetString("MetaDataView_BinaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not set&gt;.
        /// </summary>
        internal static string MetaDataView_Value_Not_Set {
            get {
                return ResourceManager.GetString("MetaDataView_Value_Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Value.
        /// </summary>
        internal static string MetaData_Add_Value {
            get {
                return ResourceManager.GetString("MetaData_Add_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Create Thumbnail Image.
        /// </summary>
        internal static string MetaData_Auto_Create_Thumbnail_Image {
            get {
                return ResourceManager.GetString("MetaData_Auto_Create_Thumbnail_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Resize Image.
        /// </summary>
        internal static string MetaData_Auto_Resize_Image {
            get {
                return ResourceManager.GetString("MetaData_Auto_Resize_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Foundation Enums.
        /// </summary>
        internal static string MetaData_Baf_Enums {
            get {
                return ResourceManager.GetString("MetaData_Baf_Enums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Foundation Meta Classes.
        /// </summary>
        internal static string MetaData_Baf_Meta_Classes {
            get {
                return ResourceManager.GetString("MetaData_Baf_Meta_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Meta classes.
        /// </summary>
        internal static string MetaData_Catalog_Meta_Classes {
            get {
                return ResourceManager.GetString("MetaData_Catalog_Meta_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is strongly recommended that you back up your ECF database before performing import..
        /// </summary>
        internal static string MetaData_Db_Backup_Recommendation {
            get {
                return ResourceManager.GetString("MetaData_Db_Backup_Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meta Class with such name already exists. Try to use another name..
        /// </summary>
        internal static string MetaData_Error_CreateMetaClass_AlreadyExists {
            get {
                return ResourceManager.GetString("MetaData_Error_CreateMetaClass_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meta Class with such friendly name already exists. Try to use another friendly name..
        /// </summary>
        internal static string MetaData_Error_CreateMetaClass_FriendlyName_AlreadyExists {
            get {
                return ResourceManager.GetString("MetaData_Error_CreateMetaClass_FriendlyName_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files available for import.
        /// </summary>
        internal static string MetaData_Files_Available_For_Import {
            get {
                return ResourceManager.GetString("MetaData_Files_Available_For_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To import meta data, please pick an existing file from the grid below or upload a new one. Then click the button &apos;Start Import&apos; to start importing..
        /// </summary>
        internal static string MetaData_Import_Instructions {
            get {
                return ResourceManager.GetString("MetaData_Import_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data Import.
        /// </summary>
        internal static string MetaData_Import_Title {
            get {
                return ResourceManager.GetString("MetaData_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing Option.
        /// </summary>
        internal static string MetaData_Indexing_Option {
            get {
                return ResourceManager.GetString("MetaData_Indexing_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Tokenized.
        /// </summary>
        internal static string MetaData_Not_Tokenized {
            get {
                return ResourceManager.GetString("MetaData_Not_Tokenized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Meta classes.
        /// </summary>
        internal static string MetaData_Order_Meta_Classes {
            get {
                return ResourceManager.GetString("MetaData_Order_Meta_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision+Scale must be &amp;lt;= 38.
        /// </summary>
        internal static string MetaData_Precision_LessThanOrEqual_38 {
            get {
                return ResourceManager.GetString("MetaData_Precision_LessThanOrEqual_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the file.
        /// </summary>
        internal static string MetaData_Save_The_File {
            get {
                return ResourceManager.GetString("MetaData_Save_The_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Properties.
        /// </summary>
        internal static string MetaData_Search_Properties {
            get {
                return ResourceManager.GetString("MetaData_Search_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Import.
        /// </summary>
        internal static string MetaData_Start_Import {
            get {
                return ResourceManager.GetString("MetaData_Start_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the value.
        /// </summary>
        internal static string MetaData_Store_The_Value {
            get {
                return ResourceManager.GetString("MetaData_Store_The_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Image.
        /// </summary>
        internal static string MetaData_Stretch_Image {
            get {
                return ResourceManager.GetString("MetaData_Stretch_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch Thumbnail Image.
        /// </summary>
        internal static string MetaData_Stretch_Thumbnail_Image {
            get {
                return ResourceManager.GetString("MetaData_Stretch_Thumbnail_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenized.
        /// </summary>
        internal static string MetaData_Tokenized {
            get {
                return ResourceManager.GetString("MetaData_Tokenized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Indicator.
        /// </summary>
        internal static string Progress_Indicator {
            get {
                return ResourceManager.GetString("Progress_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Log.
        /// </summary>
        internal static string Progress_Operation_Log {
            get {
                return ResourceManager.GetString("Progress_Operation_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Recent Reference.
        /// </summary>
        internal static string RecentReferenceMetaClassFriendlyName {
            get {
                return ResourceManager.GetString("RecentReferenceMetaClassFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecentReferenceHistory.
        /// </summary>
        internal static string RecentReferenceMetaClassName {
            get {
                return ResourceManager.GetString("RecentReferenceMetaClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Recent References.
        /// </summary>
        internal static string RecentReferenceMetaClassPluralName {
            get {
                return ResourceManager.GetString("RecentReferenceMetaClassPluralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Index.
        /// </summary>
        internal static string Search_Build_Index {
            get {
                return ResourceManager.GetString("Search_Build_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build the Search Index. This operation will build the index for items updated since last build..
        /// </summary>
        internal static string Search_Build_Instructions {
            get {
                return ResourceManager.GetString("Search_Build_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Search Provider:.
        /// </summary>
        internal static string Search_Default_Provider {
            get {
                return ResourceManager.GetString("Search_Default_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Configuration Text:.
        /// </summary>
        internal static string Search_Generated_Configuration {
            get {
                return ResourceManager.GetString("Search_Generated_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexers:.
        /// </summary>
        internal static string Search_Indexers {
            get {
                return ResourceManager.GetString("Search_Indexers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Search Providers:.
        /// </summary>
        internal static string Search_Installed_Providers {
            get {
                return ResourceManager.GetString("Search_Installed_Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Operations.
        /// </summary>
        internal static string Search_Operations {
            get {
                return ResourceManager.GetString("Search_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Index.
        /// </summary>
        internal static string Search_Rebuild_Index {
            get {
                return ResourceManager.GetString("Search_Rebuild_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild the Search Index. This operation will cause complete index rebuild..
        /// </summary>
        internal static string Search_Rebuild_Instructions {
            get {
                return ResourceManager.GetString("Search_Rebuild_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Configuration.
        /// </summary>
        internal static string Search_Settings {
            get {
                return ResourceManager.GetString("Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change To.
        /// </summary>
        internal static string Spell_Change_To {
            get {
                return ResourceManager.GetString("Spell_Change_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Check.
        /// </summary>
        internal static string Spell_Check {
            get {
                return ResourceManager.GetString("Spell_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Not in Dictionary.
        /// </summary>
        internal static string Spell_Word_Not_In_Dictionary {
            get {
                return ResourceManager.GetString("Spell_Word_Not_In_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Image.
        /// </summary>
        internal static string Template_Image {
            get {
                return ResourceManager.GetString("Template_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;b&gt;Browse&lt;/b&gt; and select file, or type file path.
        /// </summary>
        internal static string Uploader_Browse_Instructions {
            get {
                return ResourceManager.GetString("Uploader_Browse_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploading Progress.
        /// </summary>
        internal static string Uploader_File_Uploading_Progress {
            get {
                return ResourceManager.GetString("Uploader_File_Uploading_Progress", resourceCulture);
            }
        }
    }
}
