//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ContentStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning. Updating this item through Commerce Manager will overwrite any previous and pending content versions. Such content versions may have been created through other interfaces..
        /// </summary>
        internal static string Delete_Versions_Warning {
            get {
                return ResourceManager.GetString("Delete_Versions_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with such name already exists..
        /// </summary>
        internal static string DisplayTemplate_With_Name_Exists {
            get {
                return ResourceManager.GetString("DisplayTemplate_With_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new command.
        /// </summary>
        internal static string Folder_Command_Add {
            get {
                return ResourceManager.GetString("Folder_Command_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit command.
        /// </summary>
        internal static string Folder_Command_Edit {
            get {
                return ResourceManager.GetString("Folder_Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query string.
        /// </summary>
        internal static string Folder_Command_QueryString {
            get {
                return ResourceManager.GetString("Folder_Command_QueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access for all.
        /// </summary>
        internal static string Folder_FullAccess {
            get {
                return ResourceManager.GetString("Folder_FullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder/Page changes has been discarded..
        /// </summary>
        internal static string Folder_Page_Changes_Discarded {
            get {
                return ResourceManager.GetString("Folder_Page_Changes_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Page.
        /// </summary>
        internal static string Folder_Page_Create {
            get {
                return ResourceManager.GetString("Folder_Page_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create page version for this language?.
        /// </summary>
        internal static string Folder_Page_CreateConfirm {
            get {
                return ResourceManager.GetString("Folder_Page_CreateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder/Page Edit.
        /// </summary>
        internal static string Folder_Page_Edit {
            get {
                return ResourceManager.GetString("Folder_Page_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder/Page has been updated successfully..
        /// </summary>
        internal static string Folder_Page_Updated {
            get {
                return ResourceManager.GetString("Folder_Page_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Page.
        /// </summary>
        internal static string Folder_Page_View {
            get {
                return ResourceManager.GetString("Folder_Page_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Folder.
        /// </summary>
        internal static string Folder_ParentFolder {
            get {
                return ResourceManager.GetString("Folder_ParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        internal static string Folder_TargetFolder {
            get {
                return ResourceManager.GetString("Folder_TargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder/page with the specified name already exists..
        /// </summary>
        internal static string Folder_With_Name_Exists {
            get {
                return ResourceManager.GetString("Folder_With_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Language_Code {
            get {
                return ResourceManager.GetString("Language_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code (for example, en-US).
        /// </summary>
        internal static string Language_Code_Description {
            get {
                return ResourceManager.GetString("Language_Code_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language with the specified code already exists.
        /// </summary>
        internal static string Language_Code_Exists {
            get {
                return ResourceManager.GetString("Language_Code_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid language code.
        /// </summary>
        internal static string Language_Code_Invalid {
            get {
                return ResourceManager.GetString("Language_Code_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Required Field Missing&lt;/b&gt;&lt;br /&gt;A language Code is required..
        /// </summary>
        internal static string Language_Code_Required {
            get {
                return ResourceManager.GetString("Language_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        internal static string Language_Friendly_Name {
            get {
                return ResourceManager.GetString("Language_Friendly_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        internal static string Language_Is_Default {
            get {
                return ResourceManager.GetString("Language_Is_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Required Field Missing&lt;/b&gt;&lt;br /&gt;A language Name is required..
        /// </summary>
        internal static string Language_Name_Required {
            get {
                return ResourceManager.GetString("Language_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A menu item with the specified name already exists..
        /// </summary>
        internal static string MenuItem_With_Name_Exists {
            get {
                return ResourceManager.GetString("MenuItem_With_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu changes have been discarded..
        /// </summary>
        internal static string Menu_Changes_Discarded {
            get {
                return ResourceManager.GetString("Menu_Changes_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Menu_Command {
            get {
                return ResourceManager.GetString("Menu_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Menu_Command_Link {
            get {
                return ResourceManager.GetString("Menu_Command_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Menu_Command_Navigation {
            get {
                return ResourceManager.GetString("Menu_Command_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Menu_Command_None {
            get {
                return ResourceManager.GetString("Menu_Command_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Menu_Command_Parameters {
            get {
                return ResourceManager.GetString("Menu_Command_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters values divided with &apos;;&apos;.
        /// </summary>
        internal static string Menu_Command_Parameters_Description {
            get {
                return ResourceManager.GetString("Menu_Command_Parameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        internal static string Menu_Command_Script {
            get {
                return ResourceManager.GetString("Menu_Command_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string Menu_Command_String {
            get {
                return ResourceManager.GetString("Menu_Command_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command type.
        /// </summary>
        internal static string Menu_Command_Type {
            get {
                return ResourceManager.GetString("Menu_Command_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item changes have been discarded..
        /// </summary>
        internal static string Menu_Item_Changes_Discarded {
            get {
                return ResourceManager.GetString("Menu_Item_Changes_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the menu item name, it will be typically displayed on the site as a menu choice..
        /// </summary>
        internal static string Menu_Item_Name_Instructions {
            get {
                return ResourceManager.GetString("Menu_Item_Name_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Required Field Missing&lt;/b&gt;&lt;br /&gt;A menu item name is required..
        /// </summary>
        internal static string Menu_Item_Name_Required {
            get {
                return ResourceManager.GetString("Menu_Item_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order for the menu item..
        /// </summary>
        internal static string Menu_Item_Sort_Order_Description {
            get {
                return ResourceManager.GetString("Menu_Item_Sort_Order_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sort Order value..
        /// </summary>
        internal static string Menu_Item_Sort_Order_Invalid {
            get {
                return ResourceManager.GetString("Menu_Item_Sort_Order_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the menu item tooltip, it will be usually displayed when cursor is over the menu choice..
        /// </summary>
        internal static string Menu_Item_Tooltip_Instructions {
            get {
                return ResourceManager.GetString("Menu_Item_Tooltip_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item has been updated successfully..
        /// </summary>
        internal static string Menu_Item_Updated {
            get {
                return ResourceManager.GetString("Menu_Item_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the menu name. It will be used for lookup purposes and typically will not be displayed anywhere on the site. Good names are &quot;HeaderMenu&quot;, &quot;SideMenu&quot;, &quot;FooterMenu&quot;..
        /// </summary>
        internal static string Menu_Name_Instructions {
            get {
                return ResourceManager.GetString("Menu_Name_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Required Field Missing&lt;/b&gt;&lt;br /&gt;A menu name is required..
        /// </summary>
        internal static string Menu_Name_Required {
            get {
                return ResourceManager.GetString("Menu_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu has been updated successfully..
        /// </summary>
        internal static string Menu_Updated {
            get {
                return ResourceManager.GetString("Menu_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A menu with the specified name already exists..
        /// </summary>
        internal static string Menu_With_Name_Exists {
            get {
                return ResourceManager.GetString("Menu_With_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing search engines may present the content of your meta description tag as the result of a search query. Your meta description tag should be within 140 and 200 characters..
        /// </summary>
        internal static string Meta_Description_Instructions {
            get {
                return ResourceManager.GetString("Meta_Description_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (meta description).
        /// </summary>
        internal static string Meta_Description_Parenthesis {
            get {
                return ResourceManager.GetString("Meta_Description_Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (meta keywords).
        /// </summary>
        internal static string Meta_Keywords_Parenthesis {
            get {
                return ResourceManager.GetString("Meta_Keywords_Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default page.
        /// </summary>
        internal static string Page_DefaultPage {
            get {
                return ResourceManager.GetString("Page_DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specifies if the page is used as a default page for the folder it is contained in.
        /// </summary>
        internal static string Page_Default_Description {
            get {
                return ResourceManager.GetString("Page_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        internal static string Page_Drafts {
            get {
                return ResourceManager.GetString("Page_Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a &quot;keyword&quot; meta-tag to list key words for the document. Use a distinct list of keywords that relate to the specific page on your site instead of using one broad set of keywords for every page..
        /// </summary>
        internal static string Page_Keywords_Instruction {
            get {
                return ResourceManager.GetString("Page_Keywords_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Page.
        /// </summary>
        internal static string Page_MasterPage {
            get {
                return ResourceManager.GetString("Page_MasterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the page name. The .aspx extention will be auto added to the name if not specified..
        /// </summary>
        internal static string Page_Name_Instruction {
            get {
                return ResourceManager.GetString("Page_Name_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Page_Rejected {
            get {
                return ResourceManager.GetString("Page_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the title element to identify the contents of a document. A good seo title should contain your primary keyword phrase for that page and any secondary keyword phrases that you may be targeting. Try to keep it less than 64 characters..
        /// </summary>
        internal static string Page_Title_Instruction {
            get {
                return ResourceManager.GetString("Page_Title_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Approval.
        /// </summary>
        internal static string Page_WaitingApproval {
            get {
                return ResourceManager.GetString("Page_WaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Address.
        /// </summary>
        internal static string Site_Address {
            get {
                return ResourceManager.GetString("Site_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify admin url for the site (leave blank to disable admin tab).
        /// </summary>
        internal static string Site_Admin_Url_Description {
            get {
                return ResourceManager.GetString("Site_Admin_Url_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site changes has been discarded..
        /// </summary>
        internal static string Site_Changes_Discarded {
            get {
                return ResourceManager.GetString("Site_Changes_Discarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list of domains (one per line).
        /// </summary>
        internal static string Site_Domain_List {
            get {
                return ResourceManager.GetString("Site_Domain_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Edit.
        /// </summary>
        internal static string Site_Edit {
            get {
                return ResourceManager.GetString("Site_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported Files List.
        /// </summary>
        internal static string Site_Exported_Files_Description {
            get {
                return ResourceManager.GetString("Site_Exported_Files_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to export site.
        /// </summary>
        internal static string Site_Export_Instructions_Partial_1 {
            get {
                return ResourceManager.GetString("Site_Export_Instructions_Partial_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button to start..
        /// </summary>
        internal static string Site_Export_Instructions_Partial_2 {
            get {
                return ResourceManager.GetString("Site_Export_Instructions_Partial_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Folder.
        /// </summary>
        internal static string Site_Folder {
            get {
                return ResourceManager.GetString("Site_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A site folder with specified name already exists..
        /// </summary>
        internal static string Site_Folder_AlreadyExists {
            get {
                return ResourceManager.GetString("Site_Folder_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Required Field Missing&lt;/b&gt;&lt;br /&gt;A site folder is required..
        /// </summary>
        internal static string Site_Folder_Required {
            get {
                return ResourceManager.GetString("Site_Folder_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To import site, please pick up an existing file from the grid below or upload a new one. Then click the button &apos;Start Import&apos; to start importing..
        /// </summary>
        internal static string Site_Import_Instructions {
            get {
                return ResourceManager.GetString("Site_Import_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is strongly recommended that you back up your ECF database before performing import..
        /// </summary>
        internal static string Site_Import_Warning {
            get {
                return ResourceManager.GetString("Site_Import_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Site Languages.
        /// </summary>
        internal static string Site_Languages_Configure {
            get {
                return ResourceManager.GetString("Site_Languages_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A site with specified name already exists..
        /// </summary>
        internal static string Site_Name_AlreadyExists {
            get {
                return ResourceManager.GetString("Site_Name_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Required Field Missing&lt;/b&gt;&lt;br /&gt;A site name is required..
        /// </summary>
        internal static string Site_Name_Required {
            get {
                return ResourceManager.GetString("Site_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing site.
        /// </summary>
        internal static string Site_Overwrite_Existing {
            get {
                return ResourceManager.GetString("Site_Overwrite_Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page template.
        /// </summary>
        internal static string Site_Page_Template {
            get {
                return ResourceManager.GetString("Site_Page_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Site Parameters.
        /// </summary>
        internal static string Site_Parameters_Public {
            get {
                return ResourceManager.GetString("Site_Parameters_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters to identify site in the public section.
        /// </summary>
        internal static string Site_Parameters_To_Identify {
            get {
                return ResourceManager.GetString("Site_Parameters_To_Identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO Parameters.
        /// </summary>
        internal static string Site_SEO_Parameters {
            get {
                return ResourceManager.GetString("Site_SEO_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Template.
        /// </summary>
        internal static string Site_Template {
            get {
                return ResourceManager.GetString("Site_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete template because it&apos;s being used by site pages..
        /// </summary>
        internal static string Site_Template_Delete_ReferenceException {
            get {
                return ResourceManager.GetString("Site_Template_Delete_ReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete item(s). Error: .
        /// </summary>
        internal static string Site_Template_Delete_TitleException {
            get {
                return ResourceManager.GetString("Site_Template_Delete_TitleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Theme.
        /// </summary>
        internal static string Site_Theme {
            get {
                return ResourceManager.GetString("Site_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defines the source of templates and stylesheets.
        /// </summary>
        internal static string Site_Theme_Description {
            get {
                return ResourceManager.GetString("Site_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site has been updated successfully..
        /// </summary>
        internal static string Site_Updated {
            get {
                return ResourceManager.GetString("Site_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages are added and enabled in the CMS Admin view under Config and Manage website..
        /// </summary>
        internal static string Use_CMS_Languages {
            get {
                return ResourceManager.GetString("Use_CMS_Languages", resourceCulture);
            }
        }
    }
}
